--- 
title: "**Activity_3_Mahdis_Moghadasi**"
output:
  html_document:
    df_print: paged
  pdf_document: default
  word_document: default
---

# Introduction

In this activity, I want to implement the data management process for
the article I am currently working on. This article is taken from my 
master's thesis.In addition, this activity gives me the opportunity 
to change my article into a reproducible research.The article aims to *explore the relationship between accessibility through the transport
networks and the spatial structure of population and activity in Iran*.


# Project Data Analysis
_**1.List the data that you expect to use, collect or create in your project**_

he data used in this study include population, employment, employment rate, Potential accessibility,  road network, railway lines, and railway stations. 

**Data**  | **Description**
------------- | -------------
Population  | the data on the Population for 1996, 2006 and 2016 were obtained from the Statistical Center of Iran.
Employment | the data on the employment for 1996, 2006 and 2016 were obtained from the Statistical Center of Iran.
Transportation network | The road network of Iran was obtained from Iran Road Maintenance & Transportation Organization (RMTO), and the railway lines and station shapefiles were obtained from Iran's Railway Company (IRC) over the three periods of 1996, 2006, and 2016.
Employment rate | The employment rate has been calculated using the growth rate formula for the two periods 1996-2006 and 2006-2016.
Accessibility | the  potential accessibility method was applied to calculate the accessibility at the county scale using two measures of population attractiveness and activity.


_**2.Are there legal or ethicial restrictions that you will need to address?**_

As some of the data in this article, such as the rail network and railway stations across the country, may pose security risks, I am not allowed to share this data publicly.

_**3.Go through the Quick Hits for Data Management and identify possible strategies to build and protect the value of your data**_

* *keep raw data and Back up*

Raw data received from various organizations were all first organized. Then they were saved as a zip file in a cloud space called _Mega_ and A copy of the files was also saved on my hard external drive and laptop.

* *File Format&*

All files were saved in .shp, .Mxd, .doc, .pdf and .xlsx formats, but for now, I am changing all the files to .Rmd format.I also plan to save the new files in a new private repository in GateHub.

* *Create a File naming*

All files with different formats were named using the following: 
XXXXX_YYYYMMDD_v00

_Which_ XXXX means filename, YYYYMMDD means file creation time, and v00 indicates the version of files.












